<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxkznax\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxkznax/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFxkznax.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFxkznax\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFxkznax\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fxkznax',
    'container.build_id' => 'f8461f39',
    'container.build_time' => 1516276259,
));
