<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBldmpae\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBldmpae/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBldmpae.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBldmpae\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBldmpae\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bldmpae',
    'container.build_id' => '31ae72c9',
    'container.build_time' => 1516112079,
));
