<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfbmenr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfbmenr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRfbmenr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRfbmenr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRfbmenr\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rfbmenr',
    'container.build_id' => '1ca6ff36',
    'container.build_time' => 1515680016,
));
